Updated script to use getGitRepositories function, fixed issue with get_repository_name_regex

diff --git a/update-repos b/update-repos
--- a/update-repos
+++ b/update-repos
@@ -4,7 +4,7 @@
 # set -e
 
 # constants
-get_repository_name_regex='^.+\/\(.*\)\.git$'
+get_repository_name_regex='^[^\/]\+\/\/\([^\/]\+\/\)\+\([^\/]\+\)\.git$'
 get_stash_regex='^\([^:]\+\).*'
 
 # variables
@@ -69,7 +69,7 @@ getGitRepositories()
 			echo "Cannot determine root directory for an unknown reason $rootFolder" >&2 && return 128
 		fi
 	else
-		echo "not a git directory, checking child folders" >&2
+		echo "$rootFolder is not a git directory, checking child folders" >&2
 		for folder in "${rootFolder}"/*/
 		do
 			#echo "${folder}"
@@ -78,120 +78,94 @@ getGitRepositories()
 	fi
 }
 
-# shopt -s nullglob
-# walkDirectoryTree()
-# {
-# 	local rootFolder="${1}"
-# 	# cd "${root_folder}"
-# 	for folder in "${rootFolder}"/*
-# 	do
-# 		echo "${folder}"
-# 		walkDirectoryTree "$folder"
-# 	done
-# 
-# }
-
-# while IFS='' read -r git_repo
-# do
-# 	echo "${git_repo}"
-# done < <(walkDirectoryTree "${root_directory}")
-# walkDirectoryTree "${root_directory}"
-
+# script
 while IFS='' read -r git_repo
 do
-	echo "git_repo: ${git_repo}"
-done < <(getGitRepositories "${root_directory}")
+	pushd "${git_repo}" >/dev/null
+	echo "changed to directory $git_repo"
 
-# script
-#pushd ${root_directory}
-#echo "changed to directory ${root_directory}"
-#
-#for folder in */
-#do
-#	pushd "${folder}"
-#	echo "changed to directory $folder"
-#
-#	IFS='' read -ra existing_remotes <<< $(git remote)
-#
-#	echo "existing remotes: ${existing_remotes[@]}"
-#
-#	if ! elementIn "${remote}" "${existing_remotes[@]}"
-#	then
-#		echo "${remote} does not exist!"
-#		echo "Skipping this repository."
-#		popd
-#		continue
-#	fi
-#
-#	remote_url=$(git remote get-url "${remote}")
-#	repository_name=$(echo "${remote_url}" | sed 's/'"${get_repository_name_regex}"'/\1/')
-#
-#	echo "remote url: ${remote_url}"
-#	echo "repository name: ${repository_name}"
-#
-#	if [[ ${repository_name} == ${remote_url} ]]
-#	then
-#		echo "Skipping this repository since $remote_url does not look like a valid git remote url"
-#		popd
-#		continue
-#	fi
-#
-#	shopt -s nocasematch
-#
-#	if [[ ! ${repository_name} =~ ${repository_name_regex} ]]
-#	then
-#		echo "Skipping ${repository_name} since it does not match the given regex ${repository_name_regex}"
-#		popd
-#		continue
-#	fi
-#
-#	shopt -u nocasematch
-#
-#	echo 'fetching new content for '"${remote_url}"
-#	git fetch --tags --prune "${remote_url}" "${branches[@]}"
-#
-#	if [[ ! $? -eq 0 ]]
-#	then
-#		echo "One or multiple branches of ${branches[@]} were not found on the remote."
-#		echo "Skipping this repository."
-#		popd
-#		continue
-#	fi
-#
-#	initialBranch="$(git rev-parse --abbrev-ref HEAD)"
-#	stashed=false
-#
-#	for branch in "${branches[@]}"
-#	do
-#		echo "checking out branch $branch"
-#		git checkout "${branch}"
-#
-#		if [[ ! $? -eq 0 ]]
-#		then
-#			stashMessage="$(date +"%Y-%m-%d_%H-%M-%S"): uncommitted changes on branch $(git rev-parse --abbrev-ref HEAD)"
-#			git stash push -m "${stashMessage}"
-#			stashed=true
-#			git checkout "${branch}"
-#		fi
-#
-#		if [[ "${ff_only}" = true ]]
-#		then
-#			echo "fast foward merging with ${remote}/${branch}"
-#			git merge --ff-only "${remote}"/"${branch}"
-#		else
-#			echo "merging with ${remote}/${branch}"
-#			git merge "${remote}"/"${branch}"
-#		fi
-#	done
-#
-#	git checkout "${initialBranch}"
-#	if $stashed
-#	then
-#		# use the stash where message matches the stashMessage instead
-#		ourStash=$(git stash list | grep "${stashMessage}" | sed 's/'"${get_stash_regex}"'/\1/')
-#		echo "Stash containing uncommitted work tree changes: $ourStash"
-#		git stash pop "${ourStash}"
-#	fi
-#
-#	popd
-#done
+	IFS='' read -ra existing_remotes <<< $(git remote)
+
+	echo "existing remotes: ${existing_remotes[@]}"
+
+	if ! elementIn "${remote}" "${existing_remotes[@]}"
+	then
+		echo "${remote} does not exist!"
+		echo "Skipping this repository."
+		popd >/dev/null
+		continue
+	fi
+
+	remote_url=$(git remote get-url "${remote}")
+	repository_name=$(echo "${remote_url}" | sed 's/'"${get_repository_name_regex}"'/\2/')
+
+	echo "remote url: ${remote_url}"
+	echo "repository name: ${repository_name}"
+
+	if [[ ${repository_name} == ${remote_url} ]]
+	then
+		echo "Skipping this repository since $remote_url does not look like a valid git remote url"
+		popd >/dev/null
+		continue
+	fi
+
+	shopt -s nocasematch
+
+	if [[ ! ${repository_name} =~ ${repository_name_regex} ]]
+	then
+		echo "Skipping ${repository_name} since it does not match the given regex ${repository_name_regex}"
+		popd >/dev/null
+		continue
+	fi
+
+	shopt -u nocasematch
+
+	echo 'fetching new content for '"${remote_url}"
+	git fetch --tags --prune "${remote_url}" "${branches[@]}"
+
+	if [[ ! $? -eq 0 ]]
+	then
+		echo "One or multiple branches of ${branches[@]} were not found on the remote."
+		echo "Skipping this repository."
+		popd >/dev/null
+		continue
+	fi
+
+	initialBranch="$(git rev-parse --abbrev-ref HEAD)"
+	stashed=false
+
+	for branch in "${branches[@]}"
+	do
+		echo "checking out branch $branch"
+		git checkout "${branch}"
+
+		if [[ ! $? -eq 0 ]]
+		then
+			stashMessage="$(date +"%Y-%m-%d_%H-%M-%S"): uncommitted changes on branch $(git rev-parse --abbrev-ref HEAD)"
+			git stash push -m "${stashMessage}"
+			stashed=true
+			git checkout "${branch}"
+		fi
+
+		if [[ "${ff_only}" = true ]]
+		then
+			echo "fast foward merging with ${remote}/${branch}"
+			git merge --ff-only "${remote}"/"${branch}"
+		else
+			echo "merging with ${remote}/${branch}"
+			git merge "${remote}"/"${branch}"
+		fi
+	done
+
+	git checkout "${initialBranch}"
+	if $stashed
+	then
+		# use the stash where message matches the stashMessage instead
+		ourStash=$(git stash list | grep "${stashMessage}" | sed 's/'"${get_stash_regex}"'/\1/')
+		echo "Stash containing uncommitted work tree changes: $ourStash"
+		git stash pop "${ourStash}"
+	fi
+
+	popd >/dev/null
+
+done < <(getGitRepositories "${root_directory}")
